var citiesCode = [
    { "name": "Amnat Charoen", "cityCode": 571 },
    { "name": "Ang Thong", "cityCode": 218 },
    { "name": "Bangkok", "cityCode": 219 },
    { "name": "Bueng Kan", "cityCode": 590 },
    { "name": "Buri Ram", "cityCode": 572 },
    { "name": "Cha-am", "cityCode": 241 },
    { "name": "Chachoengsao", "cityCode": 220 },
    { "name": "Chainat", "cityCode": 221 },
    { "name": "Chaiyaphum", "cityCode": 573 },
    { "name": "Chanthaburi", "cityCode": 463 },
    { "name": "Chiang Mai", "cityCode": 101 },
    { "name": "Chiang Rai", "cityCode": 102 },
    { "name": "Chon Buri", "cityCode": 464 },
    { "name": "Chumphon", "cityCode": 343 },
    { "name": "Hat Yai", "cityCode": 362 },
    { "name": "Hua Hin", "cityCode": 240 },
    { "name": "Kalasin", "cityCode": 574 },
    { "name": "Kamphaeng Phet", "cityCode": 103 },
    { "name": "Kanchanaburi", "cityCode": 222 },
    { "name": "Khon Kaen", "cityCode": 575 },
    { "name": "Ko Chang", "cityCode": 467 },
    { "name": "Ko Kut", "cityCode": 470 },
    { "name": "Ko Lanta", "cityCode": 357 },
    { "name": "Ko Pha-ngan", "cityCode": 358 },
    { "name": "Ko Phi Phi", "cityCode": 359 },
    { "name": "Ko Samet", "cityCode": 468 },
    { "name": "Ko Samui", "cityCode": 360 },
    { "name": "Ko Tao", "cityCode": 361 },
    { "name": "Krabi", "cityCode": 344 },
    { "name": "Lampang", "cityCode": 104 },
    { "name": "Lamphun", "cityCode": 105 },
    { "name": "Loei", "cityCode": 576 },
    { "name": "Lop Buri", "cityCode": 223 },
    { "name": "Mae Hong Son", "cityCode": 106 },
    { "name": "Maha Sarakham", "cityCode": 577 },
    { "name": "Mukdahan", "cityCode": 578 },
    { "name": "Nakhon Nayok", "cityCode": 224 },
    { "name": "Nakhon Pathom", "cityCode": 225 },
    { "name": "Nakhon Phanom", "cityCode": 579 },
    { "name": "Nakhon Ratchasima", "cityCode": 580 },
    { "name": "Nakhon Sawan", "cityCode": 107 },
    { "name": "Nakhon Si Thammarat", "cityCode": 345 },
    { "name": "Nan", "cityCode": 108 },
    { "name": "Narathiwat", "cityCode": 346 },
    { "name": "Nong Bua Lam Phu", "cityCode": 581 },
    { "name": "Nong Khai", "cityCode": 582 },
    { "name": "Nonthaburi", "cityCode": 226 },
    { "name": "Pathum Thani", "cityCode": 227 },
    { "name": "Pattani", "cityCode": 347 },
    { "name": "Pattaya", "cityCode": 469 },
    { "name": "Phang Nga", "cityCode": 348 },
    { "name": "Phatthalung", "cityCode": 349 },
    { "name": "Phayao", "cityCode": 109 },
    { "name": "Phetchabun", "cityCode": 110 },
    { "name": "Phetchaburi", "cityCode": 228 },
    { "name": "Phichit", "cityCode": 111 },
    { "name": "Phitsanulok", "cityCode": 112 },
    { "name": "Phra Nakhon Si Ayutthaya", "cityCode": 229 },
    { "name": "Phrae", "cityCode": 113 },
    { "name": "Phuket", "cityCode": 350 },
    { "name": "Prachin Buri", "cityCode": 230 },
    { "name": "Prachuap Khiri Khan", "cityCode": 231 },
    { "name": "Pran Buri", "cityCode": 242 },
    { "name": "Ranong", "cityCode": 351 },
    { "name": "Ratchaburi", "cityCode": 232 },
    { "name": "Rayong", "cityCode": 465 },
    { "name": "Roi Et", "cityCode": 583 },
    { "name": "Sa Kaeo", "cityCode": 233 },
    { "name": "Sakon Nakhon", "cityCode": 584 },
    { "name": "Samut Prakan", "cityCode": 234 },
    { "name": "Samut Sakhon", "cityCode": 235 },
    { "name": "Samut Songkhram", "cityCode": 236 },
    { "name": "Saraburi", "cityCode": 237 },
    { "name": "Satun", "cityCode": 352 },
    { "name": "Si Sa Ket", "cityCode": 585 },
    { "name": "Sing Buri", "cityCode": 238 },
    { "name": "Songkhla", "cityCode": 353 },
    { "name": "Sukhothai", "cityCode": 114 },
    { "name": "Suphan Buri", "cityCode": 239 },
    { "name": "Surat Thani", "cityCode": 354 },
    { "name": "Surin", "cityCode": 586 },
    { "name": "Tak", "cityCode": 115 },
    { "name": "Trang", "cityCode": 355 },
    { "name": "Trat", "cityCode": 466 },
    { "name": "Ubon Ratchathani", "cityCode": 587 },
    { "name": "Udon Thani", "cityCode": 588 },
    { "name": "Uthai Thani", "cityCode": 116 },
    { "name": "Uttaradit", "cityCode": 117 },
    { "name": "Yala", "cityCode": 356 },
    { "name": "Yasothon", "cityCode": 589 }
];
var monthNames = ["January", "February", "March", "April", "May", "June",
    "July", "August", "September", "October", "November", "December"
];

module.exports.citiesCode = citiesCode;
module.exports.monthNames = monthNames;